/*
Package operator GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package operator

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Account) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "User":
			return []string{}, true
		case "AccountType":
			return []string{}, true
		case "AdminRole":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.User, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v ValidAccount) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Authorization":
			return []string{
				"Bearer access_token",
			}, true
		case "AuthorizationInQuery":
			return []string{
				"Bearer access_token in query",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
