/*
Package manifest GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package manifest

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v GatewayTemplate) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Host":
			return []string{}, true
		case "Https":
			return []string{}, true
		case "AlwaysEnabled":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (SortOrder) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
