/*
Package kubepkg GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package kubepkg

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v DeleteKubepkgVersion) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Channel":
			return []string{}, true
		case "Version":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v GetKubepkgRevision) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Channel":
			return []string{}, true
		case "RevisionID":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v LatestKubepkgs) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "GroupNameChannels":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v ListKubepkg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Pager":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Pager, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v ListKubepkgVersion) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Channel":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v PutKubepkgVersion) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Channel":
			return []string{}, true
		case "Data":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
