/*
Package kubepkg GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package kubepkg

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
	github_com_octohelm_kubepkg_internal_dashboard_domain_kubepkg "github.com/octohelm/kubepkg/internal/dashboard/domain/kubepkg"
	github_com_octohelm_kubepkg_pkg_apis_kubepkg_v1alpha1 "github.com/octohelm/kubepkg/pkg/apis/kubepkg/v1alpha1"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&DeleteKubepkgVersion{}))
}

func (*DeleteKubepkgVersion) ResponseContent() any {
	return nil
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&GetKubepkgRevision{}))
}

func (*GetKubepkgRevision) ResponseContent() any {
	return new(github_com_octohelm_kubepkg_pkg_apis_kubepkg_v1alpha1.KubePkg)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&LatestKubepkgs{}))
}

func (*LatestKubepkgs) ResponseContent() any {
	return new(map[string]*github_com_octohelm_kubepkg_internal_dashboard_domain_kubepkg.VersionInfo)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListKubepkg{}))
}

func (*ListKubepkg) ResponseContent() any {
	return new([]*github_com_octohelm_kubepkg_internal_dashboard_domain_kubepkg.Kubepkg)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListKubepkgVersion{}))
}

func (*ListKubepkgVersion) ResponseContent() any {
	return new([]*github_com_octohelm_kubepkg_internal_dashboard_domain_kubepkg.VersionInfo)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&PutKubepkgVersion{}))
}

func (*PutKubepkgVersion) ResponseContent() any {
	return nil
}
