/*
Package cluster GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package cluster

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
	github_com_octohelm_kubepkg_pkg_kubeutil_clusterinfo "github.com/octohelm/kubepkg/pkg/kubeutil/clusterinfo"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&GetClusterInfo{}))
}

func (*GetClusterInfo) ResponseContent() any {
	return new(github_com_octohelm_kubepkg_pkg_kubeutil_clusterinfo.ClusterInfo)
}
