/*
Package client GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package client

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v KubeClient) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Kubeconfig":
			return []string{
				"Paths to a kubeconfig. Only required if out-of-cluster.",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
