/*
Package kubeutil GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package kubeutil

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v CustomResourceDefinition) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "GroupVersion":
			return []string{}, true
		case "KindType":
			return []string{}, true
		case "ListKindType":
			return []string{}, true
		case "SpecType":
			return []string{}, true
		case "Plural":
			return []string{}, true
		case "ShortNames":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
