/*
Package operator GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package operator

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v ValidAccount) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Authorization":
			return []string{
				"Bearer access_token",
				"Totp passcode@timestamp",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
