/*
Package cluster GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package cluster

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v ListCluster) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {

		}

		return nil, false
	}
	return []string{}, true
}

func (v PutCluster) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Info":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v RenameCluster) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "NewName":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
