/*
Package auth GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package auth

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
	github_com_octohelm_courier_pkg_statuserror "github.com/octohelm/courier/pkg/statuserror"
	github_com_octohelm_kubepkg_pkg_auth "github.com/octohelm/kubepkg/pkg/auth"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&Authorize{}))
}

func (*Authorize) ResponseErrors() []error {
	return []error{
		&(github_com_octohelm_courier_pkg_statuserror.StatusErr{
			Code: 400,
			Key:  "ToAuthorizeFailed",
			Msg:  "ToAuthorizeFailed",
		}),
	}
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ExchangeToken{}))
}

func (*ExchangeToken) ResponseContent() any {
	return new(github_com_octohelm_kubepkg_pkg_auth.Token)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListAuthProvider{}))
}

func (*ListAuthProvider) ResponseContent() any {
	return new([]*github_com_octohelm_kubepkg_pkg_auth.ProviderInfo)
}
