/*
Package admin GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package admin

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
	github_com_octohelm_kubepkg_internal_dashboard_domain_account "github.com/octohelm/kubepkg/internal/dashboard/domain/account"
	github_com_octohelm_kubepkg_internal_dashboard_domain_group "github.com/octohelm/kubepkg/internal/dashboard/domain/group"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&DeleteAdminAccount{}))
}

func (*DeleteAdminAccount) ResponseContent() any {
	return nil
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListAccount{}))
}

func (*ListAccount) ResponseContent() any {
	return new(github_com_octohelm_kubepkg_internal_dashboard_domain_account.UserDataList)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListAdminAccount{}))
}

func (*ListAdminAccount) ResponseContent() any {
	return new(github_com_octohelm_kubepkg_internal_dashboard_domain_group.UserDataList)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&PutAdminAccount{}))
}

func (*PutAdminAccount) ResponseContent() any {
	return new(github_com_octohelm_kubepkg_internal_dashboard_domain_group.Account)
}
