/*
Package registry GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package registry

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&APIProxyForContainerRegistry{}))
}

func (*APIProxyForContainerRegistry) ResponseContent() any {
	return new(upgrader)
}
