/*
Package cluster GENERATED BY gengo:table 
DON'T EDIT THIS FILE
*/
package cluster

import (
	context "context"

	github_com_octohelm_storage_pkg_datatypes "github.com/octohelm/storage/pkg/datatypes"
	github_com_octohelm_storage_pkg_sqlbuilder "github.com/octohelm/storage/pkg/sqlbuilder"
)

func (Cluster) TableName() string {
	return "t_cluster"
}

func (Cluster) Primary() []string {
	return []string{
		"ID",
		"DeletedAt",
	}
}

func (Cluster) UniqueIndexes() github_com_octohelm_storage_pkg_sqlbuilder.Indexes {
	return github_com_octohelm_storage_pkg_sqlbuilder.Indexes{
		"i_name": []string{
			"Name",
		},
	}
}

func (Cluster) Indexes() github_com_octohelm_storage_pkg_sqlbuilder.Indexes {
	return github_com_octohelm_storage_pkg_sqlbuilder.Indexes{
		"i_created_at": []string{
			"CreatedAt",
		},
		"i_updated_at": []string{
			"UpdatedAt",
		},
	}
}

func init() {
	T.Add(ClusterT)
}

func (tableCluster) New() github_com_octohelm_storage_pkg_sqlbuilder.Model {
	return &Cluster{}
}

func (t *tableCluster) IsNil() bool {
	return t.table.IsNil()
}

func (t *tableCluster) Ex(ctx context.Context) *github_com_octohelm_storage_pkg_sqlbuilder.Ex {
	return t.table.Ex(ctx)
}

func (t *tableCluster) TableName() string {
	return t.table.TableName()
}

func (t *tableCluster) F(name string) github_com_octohelm_storage_pkg_sqlbuilder.Column {
	return t.table.F(name)
}

func (t *tableCluster) K(name string) github_com_octohelm_storage_pkg_sqlbuilder.Key {
	return t.table.K(name)
}

func (t *tableCluster) Cols(names ...string) github_com_octohelm_storage_pkg_sqlbuilder.ColumnCollection {
	return t.table.Cols(names...)
}

func (t *tableCluster) Keys(names ...string) github_com_octohelm_storage_pkg_sqlbuilder.KeyCollection {
	return t.table.Keys(names...)
}

type tableCluster struct {
	I               indexNameOfCluster
	table           github_com_octohelm_storage_pkg_sqlbuilder.Table
	ID              github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[ID]
	Name            github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[string]
	Desc            github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[string]
	EnvType         github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[EnvType]
	AgentInfo       github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[AgentInfo]
	AgentSecureInfo github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[AgentSecureInfo]
	NetType         github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[NetType]
	Endpoint        github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[string]
	CreatedAt       github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[github_com_octohelm_storage_pkg_datatypes.Timestamp]
	UpdatedAt       github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[github_com_octohelm_storage_pkg_datatypes.Timestamp]
	DeletedAt       github_com_octohelm_storage_pkg_sqlbuilder.TypedColumn[github_com_octohelm_storage_pkg_datatypes.Timestamp]
}

type indexNameOfCluster struct {
	Primary github_com_octohelm_storage_pkg_sqlbuilder.ColumnCollection
	IName   github_com_octohelm_storage_pkg_sqlbuilder.ColumnCollection
}

var ClusterT = &tableCluster{
	ID:              github_com_octohelm_storage_pkg_sqlbuilder.CastCol[ID](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("ID")),
	Name:            github_com_octohelm_storage_pkg_sqlbuilder.CastCol[string](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("Name")),
	Desc:            github_com_octohelm_storage_pkg_sqlbuilder.CastCol[string](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("Desc")),
	EnvType:         github_com_octohelm_storage_pkg_sqlbuilder.CastCol[EnvType](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("EnvType")),
	AgentInfo:       github_com_octohelm_storage_pkg_sqlbuilder.CastCol[AgentInfo](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("AgentInfo")),
	AgentSecureInfo: github_com_octohelm_storage_pkg_sqlbuilder.CastCol[AgentSecureInfo](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("AgentSecureInfo")),
	NetType:         github_com_octohelm_storage_pkg_sqlbuilder.CastCol[NetType](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("NetType")),
	Endpoint:        github_com_octohelm_storage_pkg_sqlbuilder.CastCol[string](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("Endpoint")),
	CreatedAt:       github_com_octohelm_storage_pkg_sqlbuilder.CastCol[github_com_octohelm_storage_pkg_datatypes.Timestamp](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("CreatedAt")),
	UpdatedAt:       github_com_octohelm_storage_pkg_sqlbuilder.CastCol[github_com_octohelm_storage_pkg_datatypes.Timestamp](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("UpdatedAt")),
	DeletedAt:       github_com_octohelm_storage_pkg_sqlbuilder.CastCol[github_com_octohelm_storage_pkg_datatypes.Timestamp](github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).F("DeletedAt")),

	I: indexNameOfCluster{
		Primary: github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).Cols([]string{
			"ID",
			"DeletedAt",
		}...),
		IName: github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}).Cols([]string{
			"Name",
		}...),
	},
	table: github_com_octohelm_storage_pkg_sqlbuilder.TableFromModel(&Cluster{}),
}
