/*
Package cueutil GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package cueutil

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Field) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Omitempty":
			return []string{}, true
		case "Tags":
			return []string{}, true
		case "Type":
			return []string{}, true
		case "Loc":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
