/*
Package dashboard GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package dashboard

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v AuthProvider) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Provider":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Provider, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Database) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Database":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Database, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Server) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Server":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.Server, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}
