/*
Package repository GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package repository

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v GroupAccountRepository) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v GroupEnvDeploymentRepository) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "GroupEnv":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v GroupEnvRepository) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
