/*
Package datatypes GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package datatypes

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v CreationTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {

		}

		return nil, false
	}
	return []string{}, true
}

func (v CreationUpdationDeletionTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreationUpdationTime":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.CreationUpdationTime, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v CreationUpdationTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreationTime":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.CreationTime, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v DeprecatedTime) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {

		}

		return nil, false
	}
	return []string{}, true
}

func (v Endpoint) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Scheme":
			return []string{}, true
		case "Opaque":
			return []string{}, true
		case "User":
			return []string{
				"encoded opaque data",
			}, true
		case "Host":
			return []string{
				"username and password information",
			}, true
		case "Path":
			return []string{
				"host or host:port",
			}, true
		case "RawPath":
			return []string{
				"path (relative paths may omit leading slash)",
			}, true
		case "OmitHost":
			return []string{
				"encoded path hint (see EscapedPath method)",
			}, true
		case "ForceQuery":
			return []string{
				"do not emit empty host (authority)",
			}, true
		case "RawQuery":
			return []string{
				"append a query ('?') even if RawQuery is empty",
			}, true
		case "Fragment":
			return []string{
				"encoded query values, without '?'",
			}, true
		case "RawFragment":
			return []string{
				"fragment for references, without '#'",
			}, true

		}

		return nil, false
	}
	return []string{
		"openapi:strfmt endpoint",
	}, true
}

func (v Pager) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Size":
			return []string{}, true
		case "Offset":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v PrimaryID) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{
				"自增 ID",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}
