/*
Package agent GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package agent

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v ApplyKubePkg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Authorization":
			return []string{}, true
		case "ApisKubepkgV1Alpha1KubePkg":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.ApisKubepkgV1Alpha1KubePkg, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v Client) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Endpoint":
			return []string{}, true
		case "OtpKeyURL":
			return []string{}, true
		case "Token":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v DelKubePkg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Authorization":
			return []string{}, true
		case "Name":
			return []string{}, true
		case "Namespace":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v GetClusterInfo) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Authorization":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v GetKubePkg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Authorization":
			return []string{}, true
		case "Name":
			return []string{}, true
		case "Namespace":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v ListKubePkg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Authorization":
			return []string{}, true
		case "Namespace":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
