/*
Package agent GENERATED BY gengo:client
DON'T EDIT THIS FILE
*/
package agent

import (
	context "context"

	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
	github_com_octohelm_courier_pkg_courierhttp "github.com/octohelm/courier/pkg/courierhttp"
	github_com_octohelm_kubepkg_pkg_apis_kubepkg_v1alpha1 "github.com/octohelm/kubepkg/pkg/apis/kubepkg/v1alpha1"
	github_com_octohelm_kubepkg_pkg_kubeutil_clusterinfo "github.com/octohelm/kubepkg/pkg/kubeutil/clusterinfo"
	k8s_io_apimachinery_pkg_apis_meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type GetClusterInfo struct {
	github_com_octohelm_courier_pkg_courierhttp.MethodGet `path:"/api/kubepkg-agent/v1/cluster"`

	Authorization string `name:"Authorization,omitempty" in:"header"`
}

func (r *GetClusterInfo) Do(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) github_com_octohelm_courier_pkg_courier.Result {
	return github_com_octohelm_courier_pkg_courier.ClientFromContext(ctx, "agent").Do(ctx, r, metas...)
}

func (r *GetClusterInfo) Invoke(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) (*GetClusterInfoResponse, github_com_octohelm_courier_pkg_courier.Metadata, error) {
	var resp GetClusterInfoResponse
	meta, err := r.Do(ctx, metas...).Into(&resp)
	return &resp, meta, err
}

type ListKubePkg struct {
	github_com_octohelm_courier_pkg_courierhttp.MethodGet `path:"/api/kubepkg-agent/v1/kubepkgs"`

	Authorization string `name:"Authorization,omitempty" in:"header"`

	Namespace string `name:"namespace,omitempty" in:"query"`
}

func (r *ListKubePkg) Do(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) github_com_octohelm_courier_pkg_courier.Result {
	return github_com_octohelm_courier_pkg_courier.ClientFromContext(ctx, "agent").Do(ctx, r, metas...)
}

func (r *ListKubePkg) Invoke(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) (*ListKubePkgResponse, github_com_octohelm_courier_pkg_courier.Metadata, error) {
	var resp ListKubePkgResponse
	meta, err := r.Do(ctx, metas...).Into(&resp)
	return &resp, meta, err
}

type ApplyKubePkg struct {
	github_com_octohelm_courier_pkg_courierhttp.MethodPut `path:"/api/kubepkg-agent/v1/kubepkgs"`

	Authorization string `name:"Authorization,omitempty" in:"header"`

	ApisKubepkgV1Alpha1KubePkg `in:"body" mime:"json"`
}

func (r *ApplyKubePkg) Do(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) github_com_octohelm_courier_pkg_courier.Result {
	return github_com_octohelm_courier_pkg_courier.ClientFromContext(ctx, "agent").Do(ctx, r, metas...)
}

func (r *ApplyKubePkg) Invoke(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) (github_com_octohelm_courier_pkg_courier.Metadata, error) {
	return r.Do(ctx, metas...).Into(nil)
}

type DelKubePkg struct {
	github_com_octohelm_courier_pkg_courierhttp.MethodDelete `path:"/api/kubepkg-agent/v1/kubepkgs/:name"`

	Authorization string `name:"Authorization,omitempty" in:"header"`

	Name string `name:"name" in:"path"`

	Namespace string `name:"namespace,omitempty" in:"query"`
}

func (r *DelKubePkg) Do(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) github_com_octohelm_courier_pkg_courier.Result {
	return github_com_octohelm_courier_pkg_courier.ClientFromContext(ctx, "agent").Do(ctx, r, metas...)
}

func (r *DelKubePkg) Invoke(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) (github_com_octohelm_courier_pkg_courier.Metadata, error) {
	return r.Do(ctx, metas...).Into(nil)
}

type GetKubePkg struct {
	github_com_octohelm_courier_pkg_courierhttp.MethodGet `path:"/api/kubepkg-agent/v1/kubepkgs/:name"`

	Authorization string `name:"Authorization,omitempty" in:"header"`

	Name string `name:"name" in:"path"`

	Namespace string `name:"namespace,omitempty" in:"query"`
}

func (r *GetKubePkg) Do(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) github_com_octohelm_courier_pkg_courier.Result {
	return github_com_octohelm_courier_pkg_courier.ClientFromContext(ctx, "agent").Do(ctx, r, metas...)
}

func (r *GetKubePkg) Invoke(ctx context.Context, metas ...github_com_octohelm_courier_pkg_courier.Metadata) (*GetKubePkgResponse, github_com_octohelm_courier_pkg_courier.Metadata, error) {
	var resp GetKubePkgResponse
	meta, err := r.Do(ctx, metas...).Into(&resp)
	return &resp, meta, err
}

type GetClusterInfoResponse = KubeutilClusterinfoClusterInfo

type ApisKubepkgV1Alpha1KubePkg = github_com_octohelm_kubepkg_pkg_apis_kubepkg_v1alpha1.KubePkg

type ApisMetaV1ObjectMeta = k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta

type ListKubePkgResponse = []ApisKubepkgV1Alpha1KubePkg

type KubeutilClusterinfoClusterInfo = github_com_octohelm_kubepkg_pkg_kubeutil_clusterinfo.ClusterInfo

type ApisMetaV1TypeMeta = k8s_io_apimachinery_pkg_apis_meta_v1.TypeMeta

type ApisKubepkgV1Alpha1Spec = github_com_octohelm_kubepkg_pkg_apis_kubepkg_v1alpha1.Spec

type ApisKubepkgV1Alpha1Status = github_com_octohelm_kubepkg_pkg_apis_kubepkg_v1alpha1.Status

type GetKubePkgResponse = ApisKubepkgV1Alpha1KubePkg
