// DO NOT EDIT THIS FILE DIRECTLY.
// generated by go extractor.
package v1alpha1

#Service: {
	// Ports [PortName]servicePort
	ports?: {[string]: int32}
	clusterIP?: string
	expose?:    #Expose
}

#Expose: {
	// Type NodePort | Ingress
	type: string
	// Paths [PortName]url
	paths?: {[string]: #HostPath}
}

#HostPath: string
