// DO NOT EDIT THIS FILE DIRECTLY.
// generated by go extractor.
package v1alpha1

#Service: {
	clusterIP?: string
	expose?:    #Expose
	// Ports [PortName]servicePort
	ports?: {[string]: int32}
	// Paths [PortName]BashPath
	paths?: {[string]: string}
}

#Expose: {
	// Type NodePort | Ingress
	type: string
	gateway?: [...string]
}
