// DO NOT EDIT THIS FILE DIRECTLY.
// generated by go extractor.
package v1alpha1

import pkg_k8s_io_api_rbac_v1 "k8s.io/api/rbac/v1"

#ServiceAccount: {
	scope?: #ScopeType
	rules: [...pkg_k8s_io_api_rbac_v1.#PolicyRule]
}

// +gengo:enum
#ScopeType: #ScopeTypeCluster | #ScopeTypeNamespace

#ScopeTypeCluster:   "Cluster"
#ScopeTypeNamespace: "Namespace"
