// DO NOT EDIT THIS FILE DIRECTLY.
// generated by go extractor.
package v1alpha1

#Volume: {
	mountPath: string
	// Prefix mountPath == export, use as envFrom
	prefix?:   string
	optional?: bool
	// else volumeMounts
	readOnly?: bool
	subPath?:  string
	type:      string
	// VolumeSource as opt
	opt?: #SpecObject
	// Spec when Type equals ConfigMap or Secret, could use to define data
	spec?: #SpecObject
}
