/*
Package repository GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package repository

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v AccessTokenRepository) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Account":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v AccountExchanger) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "AccountRepository":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.AccountRepository, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}
