/*
Package v1alpha1 GENERATED BY gengo:enum
DON'T EDIT THIS FILE
*/
package v1alpha1

func (DeployKind) EnumValues() []any {
	return []any{
		DeployKindCronJob, DeployKindDaemonSet, DeployKindDeployment, DeployKindJob, DeployKindStatefulSet,
	}
}
func (DigestMetaType) EnumValues() []any {
	return []any{
		DigestMetaBlob, DigestMetaManifest,
	}
}
func (ScopeType) EnumValues() []any {
	return []any{
		ScopeTypeCluster, ScopeTypeNamespace,
	}
}
