/*
Package clusterinfo GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package clusterinfo

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v ClusterInfo) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Nodes":
			return []string{}, true
		case "Images":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v ClusterNode) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "NodeSystemInfo":
			return []string{}, true
		case "Role":
			return []string{}, true
		case "Hostname":
			return []string{}, true
		case "InternalIP":
			return []string{}, true
		case "ExternalIP":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.NodeSystemInfo, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}
