/*
Package operator GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package operator

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Group) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "RoleType":
			return []string{
				"TODO added group role",
			}, true

		}
		if doc, ok := runtimeDoc(v.Group, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v ValidGroup) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "GroupName":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
