/*
Package clusteragent GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package clusteragent

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&RegisterClusterAgent{}))
}

func (*RegisterClusterAgent) ResponseContent() any {
	return nil
}
