name: ci

on:
  push:
    branches:
      - "*"
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DAGGER_LOG_FORMAT: plain
      GH_USERNAME: ${{ github.actor }}
      GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - run: curl -sSLf https://raw.githubusercontent.com/octohelm/wagon/main/install.sh | sudo sh

      - run: make build.webapp
      - run: make ship
      - run: make archive

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          files: |
            .wagon/build/*.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            .wagon/build/*.tar.gz
