name: Release Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - kubepkg

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build or Push Images
        env:
          GOARCH: arm64 amd64
        run: |-
          export SHA=${{ github.sha }}
          export COMMIT_SHA=${SHA:7}
          export TAG=${COMMIT_SHA}
          if [[ ${{ github.ref }} == "refs/tags/v"* ]]; then
            export TAG=$(echo ${{ github.ref }} | sed -e "s/refs\/tags\/v//")
          fi
          make docker.push TARGET=${{ matrix.target }}