name: Release Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - kubepkg

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build or Push Images
        env:
          GIT_SHA: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
          TARGET_EXEC: ${{ matrix.target }}
          TARGET_ARCH: arm64 amd64
        run: make docker.push