/*
Package agent GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package agent

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v Agent) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Endpoint":
			return []string{}, true
		case "Token":
			return []string{}, true
		case "OtpKeyURL":
			return []string{}, true
		case "Labels":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
